config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users
  resources :favorites, only: [:create, :destroy]
  resources :blogs do
    collection do
      post :confirm
      get  :person
      get  :favorite
    end
  end
  root to: "blogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :image, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true
  validates :number1, numericality: true, length: { in: 10..11 }, on: :update
  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :profile, ProfileUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    added_attrs = [:name, :username, :introduce, :number1, :profile, :remove_profile]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blogs = Blog.page(params[:page])
  end
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end
  
  def create
    @blog = current_user.blogs.new(blog_params)
    if @blog.save
      BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice:"ブログを作成しました"
    else
      render 'new'
    end
  end
  
  def confirm
    @blog = current_user.blogs.new(blog_params)
    render :new if @blog.invalid?
  end
  
  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
  
  def edit
    if @blog.user_id != current_user.id
      redirect_to blogs_path, notice: "ブログ編集の許可がありません."
    end
  end
  
  def update
    if @blog.user_id == current_user.id
      respond_to do |format|
        if @blog.update(blog_params)
          format.html { redirect_to blogs_path, notice: "ブログを編集しました"}
        else
          format.html{ render :edit }
        end
      end
    else
      redirect_to edit_blog_path, notice: "ブログ編集の許可がありません."
    end
  end
  
  def destroy
    if @blog.user_id == current_user.id
    @blog.destroy
      msg = "ブログは削除されました"
    else
      msg = "許可されていません"
    end
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def person
    @blogs = Blog.all
  end
  
  def favorite
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{@favorite.blog.user.username}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.username}さんのブログをお気に入り解除しました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only: [:edit, :update]
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      format.html { redirect_to blogs_path, notice: "ブログを編集しました" }
    else
      format.html { render :edit }
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :username, :profile, :profile_cache, :remove_profile, :introduce, :number1, :email, :password, :password_confirmation)
  end
  
  def user_set
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model:@blog, local: true , url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id = "error_explanation">
      <h4><%=@blog.errors.count %>件のエラーあります。</h4>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :投稿 %>
    <%= form.text_area :content, placeholder:"今なにしてる？", class:"form-control", rows: 5 %>
  </div>
  <div class="field">
    <%= form.label :画像 %><br>
    <%= image_tag(@blog.image, :width => "400px", class:"mb-5") if @blog.image %>
    <%= form.file_field :image, class:"form-control" %>
    <%= form.hidden_field :image_cache, class:"form-control" %>
  </div>
  <div class="col-3">
    <%= form.submit "シェア", class:"btn btn-lg btn-success my-3" %>
  </div>
<% end %>

<%= link_to "ブログ一覧画面に戻る", blogs_path, class:"btn btn-lg btn-light mb-5" %>

app/views/blogs/confirm.html.erb
<div class="container">
  <h3>以下の内容で、送信する。</h3>

  <%= form_with(model: @blog, url: blogs_path, local: true, multipart: true) do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <p><%= simple_format(@blog.content) %></p><br>
    <div class="main_picture">
      <p><%= image_tag(@blog.image) %></P>
    </div>
    <div class="col-5">
      <%= form.submit  "投稿する", class:"btn btn-ml btn-success" %>
    </div>
  <% end %>
  
  <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <div class="col-5">
      <%= form.submit "もどる", name: 'back', class:"btn btn-ml btn-info mb-5" %>
    </div>
  <% end %>
</div>

app/views/blogs/edit.html.erb
<div class="col-md-6 offset-3">
  <h2>ブログを編集する</h2>
  <%= render 'form' %>
</div>

app/views/blogs/favorite.html.erb
<div class="col-md-6 offset-3">
  <%= render "shared/information" %>
  <table class="table-light mt-3 mb-5 p-4">
    <% current_user.favorites.each do |favorite| %>
      <tr>
        <td>フォローユーザー名：<%= favorite.blog.user.username %><br></td>
      </tr>
      <tr>
        <td class="picture">
          <%= link_to image_tag(favorite.blog.image_url,:width => "400px"), blog_path(favorite.blog.id) %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/blogs/index.html.erb
<div class="col-md-6 offset-3">
  <% if user_signed_in? %>
    ユーザー名：<%= current_user.username %><br>
  <% end %>
  
  <table class="table-light mt-3 mb-5 p-4">
    <h5 class="mt-3 ml-2">投稿一覧</h5>
    <% @blogs.each do |blog| %>
      <tr>
        <% if blog.user.profile.present? %>
          <td class="personal_picture"><%= link_to image_tag(blog.user.profile_url,:width => "60px"), blog_path(blog.id) %></td>
          <td class="name"><%= blog.user.username %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= blog.created_at.strftime('%Y年%m月%d日 %H時%M分%S秒') %></td>
      </tr>
      <tr>
        <td class="picture">
          <%=link_to image_tag(blog.image_url,:width => "400px"), blog_path(blog.id) %>
        </td>
      </tr>
      <tr>
        <td class="content"><%= blog.content %></td>
      </tr>
    <% end %>
  </table>
  <div class="paginate">
    <%= paginate @blogs, class:"mb-5" %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="col-md-6 offset-3">
  <h2>ブログを作成する</h2>
  <%= render 'form' %>
</div>

app/views/blogs/person.html.erb
<div class="col-md-6 offset-3">
  <%= render "shared/information" %>
  <table class="table-light mt-3 mb-5 p-4">
    <% @blogs.each do |blog| %>
      <% if user_signed_in? && blog.user_id == current_user.id %>
        <td><%= blog.created_at.strftime('%Y年%m月%d日 %H時%M分%S秒') %></td>
        <td><%= link_to "ブログ編集", edit_blog_path(blog.id), class:"btn btn-ml btn-info pl-3" %></td>
        <td><%= link_to "ブログ削除", blog_path(blog.id), method: :delete, data: {confirm: "本当に削除してもいいですか？"}, class:"btn btn-ml btn-danger pl-3" %></td>
        <tr>
          <td class="picture">
            <%=link_to image_tag(blog.image_url,:width => "300px"), blog_path(blog.id) %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/blogs/show.html.erb
<div class="col-md-6 offset-3">
  <h3>ブログ詳細画面</h3>
  <%= link_to 'トップページ', root_path, class:"btn btn-ml btn-light" %><br>
  <% if user_signed_in? && @blog.user_id == current_user.id %>
    <%= link_to '投稿者情報', person_blogs_path, class:"btn btn-ml btn-light" %><br>
    <%= link_to '編集する', edit_blog_path(@blog), class:"btn btn-ml btn-info m-3" %>
    <%= link_to '削除する', blog_path(@blog), method: :delete, data: {confirm: "本当に削除してもいいですか？"}, class:"btn btn-ml btn-danger m-3" %>
  <% end %>
  <table>
    <tr>
      <td>
        <div class="main_picture">
          <p><%= image_tag @blog.image.url %></p>
        </div>
      </td>
      <td class="user_information">
        <div class="name">
          ユーザーネーム：<%= @blog.user.username %><br>
        </div>
        <div class="content">
          <p><%= simple_format(@blog.content) %></p>
        </div>
      </td>
    </tr>
  </table>
  
  <% unless @blog.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger mb-3' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary mb-3' %>
    <% end %>
    <div class="favorite_btn">
      <%= link_to "お気に入り投稿に戻る", favorite_blogs_path, class:"btn btn-md btn-light" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom">
  <div class="container-fluid bg-light py-2">
    <div class="container">
      <div class="col-md-4">
        <div class="row">
          <div class="col-sm-10">
            <% if user_signed_in? %>
              <a href="/" class="text-dark pr-4", style="text-decoration: none">Top</a>
            <% else %>
              <a href="/" class="text-dark pr-4", style="text-decoration: none">Top</a>
              <a href="/users/sign_up" class="text-dark", style="text-decoration: none">新規作成</a>
              <a href="/users/sign_in" class="text-dark pl-3", style="text-decoration: none">ログイン</a>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to root_path do %>
          <i class="fa fa-camera"></i> Instagram
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-key"></i> プロフィール・パスワードの変更
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to new_blog_path do %>
              <i class="fa fa-envelope"></i>投稿
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to person_blogs_path do %>
              <i class="fa fa-user"></i>投稿実績
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to favorite_blogs_path do %>
              <i class="fa fa-heart"></i> お気に入り投稿
            <% end %>
          </li>
          <li class="nav-item active logout">
            <%= link_to destroy_user_session_path, :method => :delete do %>
              <i class="fa fa-sign-out"></i> ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stamp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% if user_signed_in? %>
      <%= render "shared/messages" %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_information.html.erb
<% if user_signed_in? %>
  <table>
    <tbody>
      <tr>
        <% if current_user.profile? %>
          <td class="personal_picture">
            <% if current_user.profile.present? %>
              <%= image_tag(current_user.profile_url,:width => "60px") %>
            <% end %>
          </td>
        <% end %>
        <td class="space">
          <div class="font">
            <%= current_user.username %><br>
            <%= current_user.introduce %><br>
            投稿数: <%= current_user.blogs.count %><br>
            いいね件数: <%= current_user.favorites.count %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/shared/_messages.html.erb
<div class="col-md-6 offset-3">
  <div class="notice">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</div>